# Generated by Django 4.2.16 on 2024-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100)),
                ('instrument_description', models.TextField()),
                ('owned_by', models.CharField(max_length=100)),
            ],
        ),
    ]
