# Generated by Django 4.2.16 on 2024-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_description',
        ),
        migrations.AddField(
            model_name='instrument',
            name='Comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='maintenance_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='purchased_On',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='owned_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
