# Generated by Django 4.2.16 on 2024-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
