# Generated by Django 4.2.16 on 2024-10-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_category_remove_instrument_instrument_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='Comments',
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='Inventory.category'),
        ),
    ]
